### ISSUE TITLE
Issue with Notification providers

### ISSUE THREAD

**Issue by AvinashMudunuri** [rpuls/medusajs-2.0-for-railway-boilerplate#13]
@rpuls, firstly thank you for this repo its a lifesaver.

I am integrating notifications into my project, as mentioned in the documentation and video that followed the same for Resend and SendGrid.

##Resend, created an account in resend, added RESEND_API_KEY, RESEND_FROM_EMAIL in variables section and redeployed the backend. I triggered invite-user and order-placed workflows and am getting an error as the notification provider is unavailable.

verified in database, notification table there is no entry for resend

##SendGrid, I have tried with SendGrid as well, added required variables redeployed backed, able to see the sendgrid in the notification table aswell. But, getting error as templateId should be a 16 chars uniqueId not 'invite-user'. As per documentation we need to pass templateId in config, which is missing.

![image](https://github.com/user-attachments/assets/f77b19bc-968c-46df-a525-b8b2a1a619f4)

![image](https://github.com/user-attachments/assets/74c25933-4a23-4ab5-a095-16e56dbb7d0a)

Could you suggest the approach

**Comment by rpuls** [comment]
Hi. 
SendGrid is somewhat experimental at this point not 100% officially supproted - I had it working several months ago, but havent tested it since, since I started using Resend instead. So for SendGrid some additional work might be needed.

As for the Resend, this should work as described in the videos. I also tested the integration after last update. So I am thinking something with your project must deviate a little from the base template? 

When did you launch the template? And are you still running it directly on Railway?

It might be necerssary to run migrations on the db. This can be done with the medusa cli. https://docs.medusajs.com/v1/development/entities/migrations/overview

you can put the db connection string from your production database in the `/backend/.env` file and then running: `npx medusa migrations run` from the backend dir on your local setup.

**Comment by AvinashMudunuri** [comment]
@rpuls , Thank you so much, it's working now after migration. able to send mails now

**Comment by rpuls** [comment]
Excellent! Glad to hear
